version: "3.8"

services:
  feedferret:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedferret
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - AUTH_SECRET=${AUTH_SECRET:-your-secret-here}
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=https://feedferret.wollank.cloud
    volumes:
      - feedferret_db_data:/app/data

volumes:
  feedferret_db_data:
