// FiveFilters ftr-site-config parser + in-process DOM applier.
//
// ftr-site-config (github.com/fivefilters/ftr-site-config, CC0/public domain)
// is a large community dataset of per-host article-extraction rules. Each host
// file is a simple `directive: value` text format whose XPath rules point the
// extractor straight at an article's body/title/author/date subtree and list
// the chrome to strip. Where a rule exists it is far more reliable than the
// generic Defuddle/Readability heuristics, so we run it as the FIRST extraction
// tier (see lib/readability-extract.ts) and fall back to the heuristics when no
// rule matches or a rule produces too little text.
//
// We bundle a curated subset (lib/ftr-site-configs.ts, regenerated by
// scripts/gen-ftr-site-configs.mjs) and support the directives that map cleanly
// to in-process DOM work: body/title/author/date (XPath) and
// strip/strip_id_or_class (removal). Fetch-time directives (login, pagination,
// http headers, string replacement) are intentionally out of scope.
//
// Pure/testable: parsing and applying take strings/DOM and do no I/O.

import { JSDOM } from "jsdom";
import { FTR_SITE_CONFIGS } from "./ftr-site-configs";

export type FtrConfig = {
  title: string[];
  body: string[];
  author: string[];
  date: string[];
  strip: string[];
  stripIdOrClass: string[];
};

export type FtrExtraction = {
  content: string; // concatenated outerHTML of the matched body node(s)
  title: string | null;
  author: string | null;
  date: string | null;
};

// A single directive line: `key: value` (value may itself contain colons).
const DIRECTIVE = /^([a-z_]+)\s*:\s*(.*)$/i;

/**
 * Parses a ftr-site-config rule file into the directives we consume. Unknown
 * or unsupported directives (login, pagination, replace_string, …) and
 * comments are ignored. Never throws.
 */
export function parseFtrConfig(text: string): FtrConfig {
  const config: FtrConfig = {
    title: [],
    body: [],
    author: [],
    date: [],
    strip: [],
    stripIdOrClass: [],
  };
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const match = DIRECTIVE.exec(line);
    if (!match) continue;
    const key = match[1].toLowerCase();
    const value = match[2].trim();
    if (!value) continue;
    switch (key) {
      case "title":
        config.title.push(value);
        break;
      case "body":
        config.body.push(value);
        break;
      case "author":
        config.author.push(value);
        break;
      case "date":
        config.date.push(value);
        break;
      case "strip":
        config.strip.push(value);
        break;
      case "strip_id_or_class":
        config.stripIdOrClass.push(value);
        break;
      // All other directives are intentionally unsupported for in-process use.
    }
  }
  return config;
}

function normalizeHost(host: string): string {
  return host.toLowerCase().replace(/^www\./, "");
}

// Parsed-config cache keyed by bundle host, so repeated fetches from the same
// site don't re-parse the rule text.
const parsedCache = new Map<string, FtrConfig>();

/**
 * Finds the bundled ftr config for a URL's host, or null. Matching mirrors the
 * upstream naming convention: an `example.com` rule also serves `www.example.com`
 * and its sub-domains (we walk from the most specific host up to the
 * registrable domain).
 */
export function findFtrConfigForUrl(url: string): FtrConfig | null {
  let host: string;
  try {
    host = new URL(url).hostname;
  } catch {
    return null;
  }
  host = normalizeHost(host);
  // Walk from the full host up to the registrable domain: blog.example.com →
  // example.com. Stop before the bare TLD.
  let labels = host.split(".");
  while (labels.length >= 2) {
    const candidate = labels.join(".");
    const raw = FTR_SITE_CONFIGS[candidate];
    if (raw) {
      let parsed = parsedCache.get(candidate);
      if (!parsed) {
        parsed = parseFtrConfig(raw);
        parsedCache.set(candidate, parsed);
      }
      return parsed;
    }
    labels = labels.slice(1);
  }
  return null;
}

const ORDERED_NODE_SNAPSHOT = 7; // XPathResult.ORDERED_NODE_SNAPSHOT_TYPE

/** Evaluate an XPath against a document, returning matched nodes ([] on error). */
function evaluateNodes(document: Document, xpath: string): Node[] {
  try {
    const result = document.evaluate(xpath, document, null, ORDERED_NODE_SNAPSHOT, null);
    const nodes: Node[] = [];
    for (let i = 0; i < result.snapshotLength; i++) {
      const node = result.snapshotItem(i);
      if (node) nodes.push(node);
    }
    return nodes;
  } catch {
    return []; // XPath jsdom can't evaluate (unsupported fn, bad syntax) → skip.
  }
}

/** Remove a matched node from the DOM — element or attribute. */
function removeNode(node: Node): void {
  if (node.nodeType === 2 /* ATTRIBUTE_NODE */) {
    const attr = node as Attr;
    attr.ownerElement?.removeAttributeNode(attr);
    return;
  }
  (node as ChildNode).parentNode?.removeChild(node);
}

/** Plain-text value of a matched node — attribute value or element text. */
function nodeText(node: Node): string {
  if (node.nodeType === 2 /* ATTRIBUTE_NODE */) {
    return (node as Attr).value.trim();
  }
  return (node.textContent || "").trim();
}

function firstMatchText(document: Document, xpaths: string[]): string | null {
  for (const xpath of xpaths) {
    for (const node of evaluateNodes(document, xpath)) {
      const text = nodeText(node);
      if (text) return text;
    }
  }
  return null;
}

function textLength(html: string): number {
  return html
    .replace(/<[^>]*>/g, " ")
    .replace(/\s+/g, " ")
    .trim().length;
}

/**
 * Applies a ftr config to raw HTML in-process and returns the extracted body
 * (plus title/author/date when the rule provides them), or null when the rule
 * yields no usable body. `minBodyTextLength` guards against a matched-but-empty
 * body so callers can fall back to the generic extractors.
 */
export function applyFtrConfig(
  rawHtml: string,
  url: string,
  config: FtrConfig,
  minBodyTextLength = 200,
): FtrExtraction | null {
  if (config.body.length === 0) return null;

  const dom = new JSDOM(rawHtml, { url });
  const document = dom.window.document;

  // 1. Strip chrome first so it can't leak into a body subtree that contains it.
  for (const xpath of config.strip) {
    for (const node of evaluateNodes(document, xpath)) removeNode(node);
  }
  // strip_id_or_class removes any element whose id or class attribute *contains*
  // the token (upstream semantics — substring, not whole-word).
  for (const token of config.stripIdOrClass) {
    const escaped = token.replace(/"/g, '\\"');
    // Match on id or class substring via an attribute-contains XPath.
    const xpath = `//*[contains(@id, "${escaped}") or contains(@class, "${escaped}")]`;
    for (const node of evaluateNodes(document, xpath)) removeNode(node);
  }

  // 2. Body: first XPath that yields non-empty matched element(s) wins.
  let content: string | null = null;
  for (const xpath of config.body) {
    const nodes = evaluateNodes(document, xpath).filter(
      (n) => n.nodeType === 1 /* ELEMENT_NODE */,
    );
    if (nodes.length === 0) continue;
    const html = nodes.map((n) => (n as Element).outerHTML).join("\n");
    if (textLength(html) >= minBodyTextLength) {
      content = html;
      break;
    }
  }
  if (!content) return null;

  return {
    content,
    title: firstMatchText(document, config.title),
    author: firstMatchText(document, config.author),
    date: firstMatchText(document, config.date),
  };
}
