ALTER TABLE "User" ADD COLUMN "accentColor" TEXT NOT NULL DEFAULT '#5BA4CF';
ALTER TABLE "User" ADD COLUMN "secondaryColor" TEXT NOT NULL DEFAULT '#F0963C';
ALTER TABLE "Feed" ADD COLUMN "keepMinArticles" INTEGER;
