ALTER TABLE "User" ADD COLUMN "digestTimezone" TEXT NOT NULL DEFAULT 'UTC';
ALTER TABLE "User" ADD COLUMN "digestMaxArticles" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "User" ADD COLUMN "digestMinArticles" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "User" ADD COLUMN "digestLookbackHours" INTEGER;
ALTER TABLE "User" ADD COLUMN "digestGroupByFeed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "digestAiSummary" TEXT NOT NULL DEFAULT 'none';
